clf();
timings = csvread('timings - acorn jquery.txt');
timings2 = csvread('timings - esprima jquery.txt');
timings3 = csvread('timings - acorn-loose jquery.txt');
hold;
grid on;
plot(1:120, timings(1:120), 1:120, timings2(1:120), 1:120, timings3(1:120));
set(gca, 'GridLineStyle', '-');
set(gca, 'XColor', [0.7, 0.7, 0.7]);
set(gca, 'YColor', [0.7, 0.7, 0.7]);
title('Acorn/Esprima performance over time on jQuery');
xlabel('Execution #');
ylabel('Execution time (ms)');
legend('Acorn performance', 'Esprima performance', 'Acorn-loose performance');
x=[0.35 0.2];
y=[0.56 0.25];
annotation('textarrow',x,y,'String','Compilation improves performance');